// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace dotnet_app.Migrations
{
    [DbContext(typeof(DealershipContext))]
    [Migration("20260112133429_Initial_Create")]
    partial class Initial_Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dealership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_dealerships");

                    b.ToTable("dealerships", (string)null);
                });

            modelBuilder.Entity("ServiceRecord", b =>
                {
                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealership_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ServicedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("serviced_on_utc");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("DealershipId", "Id")
                        .HasName("pk_service_records");

                    b.HasIndex("DealershipId", "VehicleId")
                        .HasDatabaseName("ix_service_records_dealership_id_vehicle_id");

                    b.ToTable("service_records", (string)null);
                });

            modelBuilder.Entity("Vehicle", b =>
                {
                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealership_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("StockNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stock_number");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean")
                        .HasColumnName("used");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vin");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("year");

                    b.HasKey("DealershipId", "Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_vin");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("ServiceRecord", b =>
                {
                    b.HasOne("Dealership", "Dealership")
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_records_dealerships_dealership_id");

                    b.HasOne("Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("DealershipId", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_records_vehicles_dealership_id_vehicle_id");

                    b.Navigation("Dealership");

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
